services:
  postgres:
    image: postgres:15
    container_name: bank_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - bank_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    restart: always

volumes:
  bank_data: